### ISSUE TITLE
Bot sample issue

### ISSUE THREAD

**Issue by forresearch10** [hanzhang0116/BotDigger#6]
This code works well for the sample file but when i run this on another bot pcaps, it generates an empty result file and gives no output. I have tried on various bot pcaps available online. Is there any behavior difference in the sample file and samples available online. Any suggestions please?

**Comment by cardi** [comment]
Have you properly configured the network information? See the section of the README labeled ["Configure Network Information"](https://github.com/hanzhang0116/BotDigger#configure-network-information).

At a minimum, you need to modify the files `DNSServerList` and `NetworkPrefixes` with the relevant information. Then try running BotDigger again.

**Comment by forresearch10** [comment]
Thanks .... I will try these modifications . Can you please suggest me some good repository where I can get Ramnit samples ?

**Comment by cardi** [comment]
You're welcome. If you're still not getting results, you might have to further change the other parameters (see the README for more information).

I don't know of where one could get traces or samples of botnet traffic, outside of your favorite search engine results. Good luck!

Closing this issue.

**Comment by forresearch10** [comment]
Sorry to open the issue again ....but i am still not getting why its not producing results on my samples . Here i have attached  a screenshot of pcap file . Actually i am confused about the configuration changes .  Any suggestions?

**Comment by cardi** [comment]
Can you post the command that you're running (including the parameters), and the contents of the filename parameters?

If you haven't already, please read the README file in its entirety. It is rather lengthy and verbose, but I think it contains all the relevant information to get BotDigger running.

If you can be more specific about which parameters/configuration flags you're confused about, I can try to help.

**Comment by forresearch10** [comment]
I am only changing the network prefixes and DNSServerlist but i am not sure if they are correct or not . So can you please tell me about the changes required considering this sample pcap.

**Comment by cardi** [comment]
Can you post the contents of your `DNSServerList` and `NetworkPrefixes`?

**Comment by forresearch10** [comment]
![screenshot from 2018-04-25 14-27-10](https://user-images.githubusercontent.com/38342698/39236178-b6d1b7fc-4895-11e8-839f-0ddff977b220.png)
In this sample , i updated the network prefixes to 192.168.1.0/16 and DNSserverlist - 200.51.43.5. when in the sample code , i set enableverbose as 1,  it generates output like this
![screenshot from 2018-04-25 14-35-57](https://user-images.githubusercontent.com/38342698/39236316-2786c2a8-4896-11e8-9d1b-e6cd1998e9d2.png).
Even changing the time window doesnot works.

**Comment by cardi** [comment]
It will be very helpful if you can copy and paste (plaintext, in formatted code blocks) the relevant portions of your `.pcap` and the output of BotDigger. It's a bit more difficult to read your comments via email if the relevant information is in an image.

It looks like you're on the right track by enabling verbose mode, but I don't have any particular insight as to why BotDigger is not giving you the results you're expecting.

You might have to adjust the following parameters:
```
  -T THRESHOLDSIMILARITY, --thresholdSimilarity=THRESHOLDSIMILARITY,
            specify the similarity threshold, the default value is 0.1.

  -B THRESHOLDBOTSONECLUSTER, --thresholdBotsOneCluster=THRESHOLDBOTSONECLUSTER,
            specify the bot cluster threshold, the default value is 4.

  -w TIMEINTERVAL, --timeWindow=TIMEINTERVAL,
            specify the time window (seconds) for bot detection, default value
            is 600 seconds
```

It's possible that you could overtune the parameters for your particular sample pcap, but that is something you'll have to experiment with.
